# Generated by Django 4.0.5 on 2022-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_indexback_delete_indexpageslayder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drName', models.CharField(max_length=50, verbose_name='Dr. name')),
                ('about', models.CharField(max_length=250, verbose_name='About Dr. ')),
                ('years', models.CharField(max_length=250, verbose_name='Years ')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
    ]
