# Generated by Django 4.0.5 on 2022-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion1', models.CharField(max_length=250, verbose_name='Customer feedback ֊ 1')),
                ('opinion2', models.CharField(max_length=250, verbose_name='Customer feedback ֊ 2')),
                ('nameCustomer', models.CharField(max_length=50, verbose_name='Customer name')),
                ('aboutCustomer', models.CharField(max_length=250, verbose_name='About Customer')),
                ('img', models.ImageField(upload_to='media', verbose_name='Customer image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
